#!/bin/sh

CONFIG_FOLDER="$HOME/.config/sketchybar"
PLUGIN_FOLDER="$CONFIG_FOLDER/plugins"

source $CONFIG_FOLDER/defaults.sh           # load constants
source $CONFIG_FOLDER/main_bar.sh           # create main bar + set defaults

# Left side items
# ---------------
source $PLUGIN_FOLDER/apple_creator.sh
add_spacer spacer1
source $PLUGIN_FOLDER/workspaces_creator.sh

# Right side items
# ----------------
source $PLUGIN_FOLDER/connectivity_bar_creator.sh

# Update the bar
sketchybar --update

