#!/bin/sh

CONFIG_FOLDER="$HOME/.config/sketchybar"
PLUGIN_FOLDER="$CONFIG_FOLDER/plugins"

source $CONFIG_FOLDER/defaults.sh           # load constants
source $CONFIG_FOLDER/main_bar.sh           # create main bar + set defaults

# Load creators
source $PLUGIN_FOLDER/apple_creator.sh
source $PLUGIN_FOLDER/workspaces_creator.sh
source $PLUGIN_FOLDER/connectivity_bar_creator.sh


# Left side items
# ---------------
add_workspaces left

# Right side items
# ----------------
add_apple right
add_spacer spacer1 right
add_connectivity right


# Update the bar (i.e. run all callbacks)
sketchybar --update

