#!/bin/sh
############################
# Yabai scripting addition #
############################
yabai -m signal --add event=dock_did_restart action="sudo yabai --load-sa"
sudo yabai --load-sa

###########
# Windows #
###########
yabai -m config layout bsp                    # Binary Space Partitioning
yabai -m config window_placement second_child # new windows are placed to the right or below the focused window
yabai -m config split_ratio 0.50
yabai -m config split_type auto
yabai -m config auto_balance on
yabai -m config window_origin_display default

yabai -m config top_padding 5
yabai -m config bottom_padding 5
yabai -m config left_padding 10
yabai -m config right_padding 10
yabai -m config window_gap 5

yabai -m config window_shadow on

yabai -m config window_animation_frame_rate 120
yabai -m config window_animation_duration 0.2
yabai -m config window_opacity_duration 0.0

yabai -m config window_opacity off
yabai -m config active_window_opacity 1.0
yabai -m config normal_window_opacity 0.9

yabai -m config insert_feedback_color 0xffd75f5f

yabai -m config window_border_width 2
yabai -m config window_border_radius 12
yabai -m config window_border_blur off
yabai -m config window_border_hidpi on
yabai -m config window_border on
yabai -m config active_window_border_color 0xFFC099FF
yabai -m config normal_window_border_color 0xFF444A73

##########
# Spaces #
##########
source $HOME/dotfiles/yabai/yabai_spaces.sh
yabai -m signal --add event=display_removed action="$HOME/dotfiles/yabai/yabai_spaces.sh"
yabai -m signal --add event=display_added action="$HOME/dotfiles/yabai/yabai_spaces.sh"

##################
# mouse settings #
##################
yabai -m config mouse_modifier fn
yabai -m config mouse_action1 move   # Modifier + left-click
yabai -m config mouse_action2 resize # Modifier + right-click
yabai -m mouse_drop_action swap

yabai -m config focus_follows_mouse off
yabai -m config mouse_follows_focus off

#########################
# disable specific apps #
#########################
yabai -m rule --add app="^System Settings" sticky=on manage=off
yabai -m rule --add app="^Calculator" sticky=on manage=off
yabai -m rule --add app="^Raycast" sticky=on layer=above manage=off
yabai -m rule --add app="^Spotify" sticky=on layer=above manage=off
yabai -m rule --add app="^KeePassXC" sticky=on layer=above manage=off
yabai -m rule --add app="^ProtonVPN" sticky=on layer=above manage=off
